### ISSUE TITLE
bizarre result from PM-DH+

### ISSUE THREAD

**Issue by zhengmin317** [qrefine/qr-tests-1us0#1]
the PM-DH+ refine log file of  0.9/8.pdb  shows QM refinement ran 50 cycles.

![screen shot 2016-08-09 at 23 24 00](https://cloud.githubusercontent.com/assets/16145132/17534230/7ba1db4c-5e88-11e6-998e-5de3b4779638.png)

 more details in the file [8.log.txt](https://github.com/qrefine/qr-tests-1us0/files/409905/8.log.txt)

I figured out it happens because we double restaints_weight_scale each macro cycle  if the bond_rmsd is larger than the max_bond_rmsd(0.3). 
The C-N bond length is a known issue for semi-empirical methods, which even leads to the bond rmsd of the optimized structure exceeds the requirement (0.3)  in crystallography. 
Shall we use the same max_bond_rmsd value (0.3) or increase it for those methods having severe C-N bond length problem?

**Comment by mpwaller** [comment]
close. no longer trying PM6-DH+
